# Generated by Django 4.2.6 on 2023-10-25 07:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewPositionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("FULL-TIME", "Full-time"),
                            ("PART-TIME", "Part-time"),
                        ],
                        max_length=9,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("APPROVED", "Approved"), ("PENDING", "Pending")],
                        max_length=8,
                        null=True,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[("NEW-ROLE", "New role"), ("REPLACE", "Replace")],
                        max_length=8,
                    ),
                ),
                (
                    "education_level",
                    models.CharField(
                        choices=[
                            ("DIPLOMA", "Diploma"),
                            ("BACHELOR", "Bachelor"),
                            ("MASTER", "Master"),
                            ("DOCTORAL", "Doctoral"),
                        ],
                        default="BACHELOR",
                        max_length=8,
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("INTERNSHIP", "Internship"),
                            ("JUNIOR", "Junior"),
                            ("MID-LEVEL", "Mid-level"),
                            ("SENIOR", "Senior"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("HR", "HR"),
                            ("ML", "ML"),
                            ("VOLLABOR", "Vollabor"),
                            ("VISERA", "Visera"),
                        ],
                        max_length=8,
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("explanation", models.TextField(blank=True, null=True)),
                ("hr_approval", models.BooleanField(blank=True, null=True)),
                ("td_approval", models.BooleanField(blank=True, null=True)),
                ("budget", models.BigIntegerField()),
                (
                    "position_title",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="job.job"
                    ),
                ),
            ],
            options={
                "verbose_name": "new position",
                "verbose_name_plural": "new positions",
            },
        ),
    ]
