# Generated by Django 4.2.6 on 2023-10-30 08:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inbox", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newpositionmodel",
            name="assigned_to",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="assigned_form",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
