# Generated by Django 4.2.6 on 2023-10-30 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inbox", "0002_newpositionmodel_assigned_to"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newpositionmodel",
            name="assigned_to",
        ),
        migrations.AddField(
            model_name="newpositionmodel",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
