# Generated by Django 4.2.6 on 2023-10-30 10:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inbox", "0003_remove_newpositionmodel_assigned_to_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="newpositionmodel",
            old_name="assigned_to",
            new_name="assigned_to_td",
        ),
    ]
