# Generated by Django 4.2.6 on 2023-10-30 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inbox", "0004_rename_assigned_to_newpositionmodel_assigned_to_td"),
    ]

    operations = [
        migrations.AddField(
            model_name="newpositionmodel",
            name="interviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interviewer_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="newpositionmodel",
            name="assigned_to_td",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_to_td_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
