# Generated by Django 4.2.6 on 2023-10-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inbox", "0005_newpositionmodel_interviewer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newpositionmodel",
            name="hr_approval",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="newpositionmodel",
            name="td_approval",
            field=models.BooleanField(default=False),
        ),
    ]
