# Generated by Django 4.2.6 on 2023-10-30 11:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inbox", "0006_alter_newpositionmodel_hr_approval_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newpositionmodel",
            name="interviewer",
        ),
        migrations.AddField(
            model_name="newpositionmodel",
            name="interviewer",
            field=models.ManyToManyField(
                blank=True, null=True, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
