version: "3.9"

services:
  redis:
    container_name: ATSRedis
    image: redis:alpine3.17
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  postgres:
    container_name: ATS
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: atsdb
      POSTGRES_USER: ATS
      POSTGRES_PASSWORD: ATSystem123
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  redis-data:
  postgres-data:

