version: "3.9"

services:

  postgres:
    container_name: ATS
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: ATS
      POSTGRES_PASSWORD: ATSystem123
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

