# Generated by Django 4.2.6 on 2023-10-30 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0002_alter_job_join_date"),
        ("authentication", "0002_remove_user_active_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="job.job",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="job.role",
            ),
        ),
    ]
