# Generated by Django 4.2.6 on 2023-11-11 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CandidateModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("job", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_number", models.CharField(max_length=15)),
                ("resume", models.FileField(upload_to="resumes/")),
                ("score", models.IntegerField(blank=True, null=True)),
                ("request_date", models.CharField(max_length=15)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "last_company",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "education_level",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("province", models.CharField(blank=True, max_length=150, null=True)),
                ("location", models.CharField(blank=True, max_length=150, null=True)),
                ("marital", models.CharField(blank=True, max_length=150, null=True)),
                ("birthdate", models.IntegerField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "military_service_status",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("job_status", models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ExcelFileModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="excel/")),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="InterviewerScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField()),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="candidate.candidatemodel",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="candidate.question",
                    ),
                ),
            ],
        ),
    ]
