# Generated by Django 4.2.6 on 2023-11-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidate", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="candidatemodel",
            old_name="first_name",
            new_name="job",
        ),
        migrations.RenameField(
            model_name="candidatemodel",
            old_name="last_name",
            new_name="name",
        ),
        migrations.AddField(
            model_name="candidatemodel",
            name="link",
            field=models.CharField(default="s", max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="candidatemodel",
            name="request_date",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="candidatemodel",
            name="phone_number",
            field=models.CharField(default="1", max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="candidatemodel",
            name="resume",
            field=models.FileField(blank=True, null=True, upload_to="resumes/"),
        ),
        migrations.AlterField(
            model_name="excefilemodel",
            name="file",
            field=models.FileField(upload_to="excel/"),
        ),
    ]
