# Generated by Django 4.2.6 on 2023-11-15 17:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("candidate", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ExcelFileModel",
        ),
    ]
