# Generated by Django 4.2.6 on 2023-11-20 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("candidate", "0002_rename_interviewerscore_interviewerscoremodel_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointmentmodel",
            name="user",
        ),
        migrations.AddField(
            model_name="appointmentmodel",
            name="candidate",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="candidate.candidatemodel",
            ),
            preserve_default=False,
        ),
    ]
