# Generated by Django 4.2.6 on 2023-11-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidate", "0003_remove_appointmentmodel_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointmentmodel",
            name="interview_time",
        ),
        migrations.AddField(
            model_name="appointmentmodel",
            name="interview_end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointmentmodel",
            name="interview_start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
