# Generated by Django 4.2.6 on 2023-11-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidate", "0004_remove_appointmentmodel_interview_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidatemodel",
            name="birthdate",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
