# Generated by Django 4.2.6 on 2023-11-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidate", "0005_alter_candidatemodel_birthdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidatemodel",
            name="invitation_count",
            field=models.IntegerField(default=0),
        ),
    ]
