# Generated by Django 4.2.6 on 2023-11-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidate", "0006_candidatemodel_invitation_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidatemodel",
            name="invitation_count",
        ),
        migrations.AddField(
            model_name="candidatemodel",
            name="candidate_approval",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
