# Generated by Django 4.2.6 on 2023-11-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidate", "0007_remove_candidatemodel_invitation_count_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pass_score", models.IntegerField()),
            ],
        ),
    ]
