# Generated by Django 4.2.6 on 2023-11-25 12:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("candidate", "0008_settings"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Settings",
            new_name="SettingsModel",
        ),
    ]
