# Generated by Django 4.2.6 on 2023-11-20 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "education",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DIPLOMA", "Diploma"),
                            ("BACHELORS", "Bachelor's Degree"),
                            ("MASTERS", "Master's Degree"),
                            ("DOCTORATE", "Doctorate"),
                        ],
                        default="",
                        max_length=9,
                        null=True,
                    ),
                ),
                ("experience", models.IntegerField(blank=True, null=True)),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("HR", "HR"),
                            ("ML", "ML"),
                            ("VOLLABOR", "Vollabor"),
                            ("VISERA", "Visera"),
                        ],
                        max_length=8,
                        null=True,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="job.job",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="job.role",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("role", "department")},
            },
        ),
    ]
