# Generated by Django 4.2.6 on 2023-11-20 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("join_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Requirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("en_title", models.CharField(max_length=150, unique=True)),
                ("fa_title", models.CharField(max_length=150, unique=True)),
                ("score", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="NewPositionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("FULL-TIME", "Full-time"),
                            ("PART-TIME", "Part-time"),
                        ],
                        max_length=9,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("APPROVED", "Approved"), ("PENDING", "Pending")],
                        max_length=8,
                        null=True,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[("NEW-ROLE", "New role"), ("REPLACE", "Replace")],
                        max_length=8,
                    ),
                ),
                (
                    "education_level",
                    models.CharField(
                        choices=[
                            ("DIPLOMA", "Diploma"),
                            ("BACHELOR", "Bachelor"),
                            ("MASTER", "Master"),
                            ("DOCTORAL", "Doctoral"),
                        ],
                        default="BACHELOR",
                        max_length=8,
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("INTERNSHIP", "Internship"),
                            ("JUNIOR", "Junior"),
                            ("MID-LEVEL", "Mid-level"),
                            ("SENIOR", "Senior"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("HR", "HR"),
                            ("ML", "ML"),
                            ("VOLLABOR", "Vollabor"),
                            ("VISERA", "Visera"),
                        ],
                        max_length=8,
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("explanation", models.TextField(blank=True, null=True)),
                ("hr_approval", models.BooleanField(default=False)),
                ("td_approval", models.BooleanField(default=False)),
                ("budget", models.BigIntegerField()),
                ("is_advertised", models.BooleanField(default=False)),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "assigned_to_td",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_to_td_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "interviewer",
                    models.ManyToManyField(
                        blank=True, null=True, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "position_title",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="job.job"
                    ),
                ),
            ],
            options={
                "verbose_name": "new position",
                "verbose_name_plural": "new positions",
            },
        ),
        migrations.CreateModel(
            name="JobRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="job.job"
                    ),
                ),
                (
                    "requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="job.requirement",
                    ),
                ),
            ],
        ),
    ]
