# Generated by Django 4.2.6 on 2023-11-08 15:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobrequirement",
            old_name="requerment",
            new_name="requirement",
        ),
    ]
