# Generated by Django 4.2.6 on 2023-11-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0002_rename_requerment_jobrequirement_requirement"),
    ]

    operations = [
        migrations.RenameField(
            model_name="requirement",
            old_name="title",
            new_name="en_title",
        ),
        migrations.AddField(
            model_name="requirement",
            name="fa_title",
            field=models.CharField(default="test", max_length=150),
            preserve_default=False,
        ),
    ]
