# Generated by Django 4.2.6 on 2023-11-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0003_rename_title_requirement_en_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="newpositionmodel",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
