# Generated by Django 4.2.6 on 2023-11-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0004_newpositionmodel_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requirement",
            name="en_title",
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="fa_title",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
